# Generated by Django 5.0.6 on 2024-07-15 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0002_material_productmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.ManyToManyField(through='simpleapp.ProductMaterial', to='simpleapp.material'),
        ),
        migrations.AlterField(
            model_name='productmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='simpleapp.material'),
        ),
    ]
