# Generated by Django 5.0.6 on 2024-07-15 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0003_product_material_alter_productmaterial_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.ManyToManyField(related_name='products', through='simpleapp.ProductMaterial', to='simpleapp.material'),
        ),
        migrations.AlterField(
            model_name='productmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleapp.material'),
        ),
    ]
